apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: fullstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ivykiera/nginx-web-page-backend:v1
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DATABASE_URL
          envFrom:
            - secretRef:
                name: postgres-secret
          # If you prefer discrete vars instead of DATABASE_URL:
          # env:
          # - name: PGHOST
          #   value: "postgres-0.postgres.fullstack.svc.cluster.local"
          # - name: PGPORT
          #   value: "5432"
          # - name: PGUSER
          #   valueFrom: { secretKeyRef: { name: postgres-secret, key: POSTGRES_USER } }
          # - name: PGPASSWORD
          #   valueFrom: { secretKeyRef: { name: postgres-secret, key: POSTGRES_PASSWORD } }
          # - name: PGDATABASE
          #   valueFrom: { secretKeyRef: { name: postgres-secret, key: POSTGRES_DB } }
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: fullstack
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP
