apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: fullstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ivykiera/nginx-web-page-frontend:v1
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_URL
              value: "http://backend.fullstack.svc.cluster.local:3000"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: fullstack
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: LoadBalancer

