apiVersion: v1
kind: Namespace
metadata:
  name: fullstack
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: fullstack
type: Opaque
stringData:
  POSTGRES_PASSWORD: appsecret
  POSTGRES_USER: appuser
  POSTGRES_DB: appdb
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: fullstack
spec:
  selector:
    app: postgres
  ports:
    - name: pg
      port: 5432
      targetPort: 5432
  clusterIP: None  # headless for StatefulSet DNS
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: fullstack
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
              subPath: data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "appuser", "-d", "appdb", "-h", "127.0.0.1"]
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 30
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
